# Generated by Django 3.1.1 on 2020-09-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginhistory',
            name='user_id',
            field=models.CharField(max_length=128),
        ),
    ]
