# Generated by Django 3.1.1 on 2020-10-01 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200929_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginhistory',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
